# Change the following to your desired values:
#   __ACCOUNT_NUMBER__
#   __ECR_REGION__
#   __ECR_REPOSITORY_NAME__
#   __ECS_CONTAINER_NAME__

version: 0.2
env:
  variables:
     ECR_REGION: "us-east-1"
     ACCOUNT_NUMBER: "603836437137"
     ECR_REPOSITORY_NAME : "value"
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - pwd
      - ls -la
      - cd ./src/lex-gen-ai-demo-cdk
      - pip install -r requirements.txt -U
      - npm install nodejs
      - npm i -g aws-cdk
      - cdk --version
      - cdk synth --all
      - export AWS_REGION=$ECR_REGION
      - cdk bootstrap --trust=$ACCOUNT_NUMBER --cloudformation-execution-policies=arn:aws:iam::aws:policy/AdministratorAccess --verbose
      - aws ecr get-login-password --region $ECR_REGION  | docker login --username AWS --password-stdin $ACCOUNT_NUMBER.dkr.ecr.$ECR_REGION.amazonaws.com
      #- REPOSITORY_URI=__ACCOUNT_NUMBER__.dkr.ecr.__ECR_REGION__.amazonaws.com/__ECR_REPOSITORY_NAME__
      #- COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      #- IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...       
      - cdk deploy --all   
      #- docker build -t $REPOSITORY_URI:latest .
      #- docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      #- docker push $REPOSITORY_URI:latest
      #- docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      #- printf '[{"name”:"__ECS_CONTAINER_NAME__","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
#artifacts:
  #files: imagedefinitions.json
